### ISSUE TITLE
Pandoc Aviation Checklist Input file(s)

### ISSUE THREAD

**Issue by Creative-Difficulty** [dpwiese/.pandoc#8]
Your blogpost on generating aviation checklists (https://danielwiese.com/posts/makefile-checklists/) massively helped me out, thank you very much! However I'm having a a hard time recreating the layout and CSS (fonts, background color for headings, etc.), could you please provide the html/css input to pandoc for the example checklist in the blogpost: https://danielwiese.com/img/posts/makefile-checklists/checklist.jpg ? this would help massively! 
Kind regards,
Alex

**Comment by Creative-Difficulty** [comment]
@dpwiese

**Comment by dpwiese** [comment]
Sorry for having missed your message months back -- did you not find what you needed at [@dpwiese/checklists](https://github.com/dpwiese/checklists)?

Edit: I didn't realize I hadn't linked to the source from the blog post -- I'll go and update the post with a link to the checklist source 😅

**Comment by Creative-Difficulty** [comment]
Thank you very much! I couldn't find the repo right away. This will be a big help in making my own checklists. You seriously are amazing!
